SELECT * FROM tabela_de_produtos;

SELECT SABOR, AVG(PRECO_DE_LISTA) AS MÉDIA FROM tabela_de_produtos GROUP BY SABOR;

SELECT SABOR, MIN(PRECO_DE_LISTA) AS MÍNIMO FROM tabela_de_produtos GROUP BY SABOR;

SELECT SABOR, MAX(PRECO_DE_LISTA) AS MÁXIMO FROM tabela_de_produtos GROUP BY SABOR;

