SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS SOMA_DE_LIMITE FROM tabela_de_clientes
GROUP BY ESTADO HAVING SUM(LIMITE_DE_CREDITO) > 900000;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAXIMO, MIN(PRECO_DE_LISTA) AS MINIMO FROM
tabela_de_produtos GROUP BY EMBALAGEM;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAXIMO, MIN(PRECO_DE_LISTA) AS MINIMO FROM
tabela_de_produtos GROUP BY EMBALAGEM HAVING SUM(PRECO_DE_LISTA) <= 80;

