-- CRIANDO UM DATABASE COM PADRÃO DE CARACTERES
CREATE DATABASE db DEFAULT CHARACTER SET utf8;

-- EXCLUINDO UM DATABASE, SE EXISTE.
DROP DATABASE IF EXISTS db;

-- CRIANDO O DATABASE DO NOSSO PROJETO
CREATE DATABASE IF NOT EXISTS vendas_sucos DEFAULT CHARACTER SET utf8;

-- CRIANDO TABELA DE PRODUTOS
CREATE TABLE PRODUTOS (
	CODIGO VARCHAR(10) NOT NULL,
    DESCRITOR VARCHAR(100) NOT NULL,
    SABOR VARCHAR(50) NULL,
    TAMANHO VARCHAR(50) NULL,
    EMBALAGEM VARCHAR(50) NULL,
    PRECO_LISTA FLOAT NULL,
    PRIMARY KEY (CODIGO)
);

-- CRIANDO TABELA DE VENDEDORES
CREATE TABLE VENDEDORES (
	MATRICULA VARCHAR(5) NOT NULL,
    NOME VARCHAR(100) NULL,
    BAIRRO VARCHAR(50) NULL,
    COMISSAO FLOAT NULL,
    DATA_ADMISSAO DATE NULL,
    FERIAS BIT(1) NULL,
    PRIMARY KEY (MATRICULA)
);

-- CRIANDO TABELA DE CLIENTES
CREATE TABLE CLIENTES (
	CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(50) NULL,
    ENDERECO VARCHAR(150) NULL,
    BAIRRO VARCHAR(50) NULL,
    CIDADE VARCHAR(50) NULL,
    ESTADO VARCHAR(50) NULL,
    CEP VARCHAR(8) NULL,
    DATA_NASCIMENTO DATE NULL,
    IDADE INT NULL,
    SEXO VARCHAR(1) NULL,
    LIMITE_CREDITO FLOAT NULL,
    VOLUME_COMPRA FLOAT NULL,
    PRIMEIRA_COMPRA BIT(1) NULL,
    PRIMARY KEY (CPF)
);

-- CRIANDO A TABELA DE VENDAS
CREATE TABLE TABELA_DE_VENDAS (
	NUMERO VARCHAR(5) NOT NULL,
    DATA_VENDA DATE NULL,
    CPF VARCHAR(11) NOT NULL,
    MATRICULA VARCHAR(5) NOT NULL,
    IMPOSTO FLOAT NULL,
    PRIMARY KEY (NUMERO)
);

-- ADICIONANDO CHAVES ESTRANGEIRAS A TABELA_DE_VENDAS
ALTER TABLE TABELA_DE_VENDAS ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);

ALTER TABLE TABELA_DE_VENDAS ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);

-- ALTERANDO O NOME DE UMA TABELA
ALTER TABLE TABELA_DE_VENDAS RENAME NOTAS;

-- CRIANDO TABELA DE ITENS VENDIDOS
CREATE TABLE ITENS_NOTAS (
	NUMERO VARCHAR(5) NOT NULL,
    CODIGO VARCHAR(10) NOT NULL,
    QUANTIDADE INT NULL,
    PRECO FLOAT NULL,
    PRIMARY KEY (NUMERO, CODIGO)
);

-- CRIANDO CHAVES ESTRANGEIRAS PARA A TABELA ITENS_NOTAS
ALTER TABLE ITENS_NOTAS ADD CONSTRAINT FK_NOTAS
FOREIGN KEY (NUMERO) REFERENCES NOTAS (NUMERO);

ALTER TABLE ITENS_NOTAS ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO) REFERENCES PRODUTOS (CODIGO);

