USE vendas_sucos;

-- INSERINDO DADOS POR COMANDOS

INSERT INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES ('1040107', 'Light - 350 ml - Melância', 'Melância', '350 ml', 'Lata', 4.56);

INSERT INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES ('1040108', 'Light - 350 ml - Graviola', 'Graviola', '350 ml', 'Lata', 4.00);

INSERT INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES ('1040109', 'Light - 350 ml - Açai', 'Açai', '350 ml', 'Lata', 5.60);

INSERT INTO PRODUTOS (CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES ('1040110', 'Light - 350 ml - Laranja', 'Laranja', '350 ml', 'Lata', 3.54);

INSERT INTO PRODUTOS VALUES
	('1040111', 'Light - 350 ml - Jaca', 'Jaca', '350 ml', 'Lata', 6.00),
    ('1040112', 'Light - 350 ml - Morango', 'Morango', '350 ml', 'Lata', 8.59);

-- INSERINDO DADOS ATRAVES DE OUTRA TABELA

USE vendas_sucos;

SELECT * FROM sucos_vendas.tabela_de_produtos;

SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, EMBALAGEM, TAMANHO, SABOR,
PRECO_DE_LISTA AS PRECO_LISTA FROM sucos_vendas.tabela_de_produtos WHERE CODIGO_DO_PRODUTO NOT IN
(SELECT CODIGO FROM PRODUTOS);
    
SELECT * FROM PRODUTOS;

INSERT INTO PRODUTOS
	SELECT CODIGO_DO_PRODUTO AS CODIGO, NOME_DO_PRODUTO AS DESCRITOR, SABOR, TAMANHO, EMBALAGEM,
	PRECO_DE_LISTA AS PRECO_LISTA FROM sucos_vendas.tabela_de_produtos WHERE CODIGO_DO_PRODUTO NOT IN
(SELECT CODIGO FROM PRODUTOS);