-- UTILIZANDO VALORES DISTINTOS

SELECT DISTINCT cidade FROM tabela_de_clientes;

SELECT DISTINCT estado FROM tabela_de_clientes;

SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos WHERE SABOR = 'Laranja';

SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos WHERE SABOR = 'Manga';

-- UTILIZANDO LIMITES

SELECT * FROM tabela_de_produtos LIMIT 5;

SELECT * FROM tabela_de_produtos LIMIT 2, 5;

-- ORDENANDO REGISTROS NA SAIDA 

SELECT * FROM tabela_de_produtos ORDER BY PRECO_DE_LISTA ASC;

SELECT * FROM tabela_de_produtos ORDER BY PRECO_DE_LISTA DESC;

SELECT * FROM tabela_de_produtos ORDER BY SABOR;

-- JUNTANDO RESPOSTAS

SELECT SABOR, SUM(PRECO_DE_LISTA) FROM tabela_de_produtos GROUP BY SABOR;

SELECT SABOR, COUNT(PRECO_DE_LISTA) FROM tabela_de_produtos GROUP BY SABOR;

SELECT SABOR, MAX(PRECO_DE_LISTA) FROM tabela_de_produtos GROUP BY SABOR;

SELECT SABOR, MIN(PRECO_DE_LISTA) FROM tabela_de_produtos GROUP BY SABOR;

SELECT SABOR, AVG(PRECO_DE_LISTA) FROM tabela_de_produtos GROUP BY SABOR;

SELECT ESTADO, AVG(LIMITE_DE_CREDITO) FROM tabela_de_clientes GROUP BY ESTADO;

SELECT CIDADE, AVG(LIMITE_DE_CREDITO) FROM tabela_de_clientes GROUP BY CIDADE;

SELECT BAIRRO, AVG(LIMITE_DE_CREDITO) FROM tabela_de_clientes GROUP BY BAIRRO;

SELECT BAIRRO, AVG(LIMITE_DE_CREDITO) FROM tabela_de_clientes WHERE ESTADO = 'RJ' GROUP BY BAIRRO;

-- UTILIZANDO O HAVING

SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS SOMA_DE_LIMITE FROM tabela_de_clientes GROUP BY ESTADO
HAVING SUM(LIMITE_DE_CREDITO) > 900000;

SELECT ESTADO, AVG(LIMITE_DE_CREDITO) AS SOMA_DE_LIMITE FROM tabela_de_clientes GROUP BY ESTADO
HAVING AVG(LIMITE_DE_CREDITO) > 10000;

-- UTILIZANDO O CASE

SELECT * FROM tabela_de_produtos;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'CARO'
	WHEN PRECO_DE_LISTA >= 8 THEN 'EM CONTA'
    WHEN PRECO_DE_LISTA >= 6 THEN 'BARATO'
	ELSE 'SUPER BARATO'
END AS STATUS_DO_PRODUTO FROM tabela_de_produtos;
	














