-- COMANDO PARA SELECIONAR O SCHEMA
USE sucos_vendas;

-- SELECIONANDO TODOS OS DADOS DE UMA TABELA
SELECT * FROM tabela_de_clientes;

-- SELECIONANDO CAMPOS ESPECÍFICOS DA TABELA
SELECT CPF, NOME, IDADE, ESTADO FROM tabela_de_clientes;

-- RENOMEANDO CAMPOS DA TABELA
SELECT ESTADO AS STATE, CIDADE AS CITY FROM tabela_de_clientes;

-- SELECIONANDO DADOS ATRAVÉS DE CONDIÇÕES
SELECT * FROM tabela_de_produtos WHERE CODIGO_DO_PRODUTO = '746596';

-- EFETUANDO CONSULTAS LÓGICAS
SELECT * FROM tabela_de_produtos WHERE SABOR = 'Manga' OR SABOR = 'Laranja';

SELECT * FROM tabela_de_produtos WHERE SABOR = 'Manga' AND EMBALAGEM = 'PET';

SELECT * FROM tabela_de_produtos WHERE SABOR = 'Manga' AND PRECO_DE_LISTA < 10;

SELECT * FROM tabela_de_produtos WHERE SABOR <> 'Manga';

SELECT * FROM tabela_de_produtos WHERE NOT SABOR = 'Manga';

SELECT * FROM tabela_de_produtos WHERE SABOR IN ('Laranja', 'Manga', 'Maça');

-- UTILIZANDO O COMANDO LIKE
SELECT * FROM tabela_de_produtos WHERE SABOR LIKE '%Maça%';

SELECT CPF, NOME, IDADE FROM tabela_de_clientes WHERE NOME LIKE '%Carvalho';

-- UTILIZANDO O COMANDO DISTINCT
SELECT DISTINCT CIDADE FROM tabela_de_clientes;

SELECT DISTINCT ESTADO FROM tabela_de_clientes;

SELECT DISTINCT SABOR FROM tabela_de_produtos;

SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos;

SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos WHERE SABOR = 'Laranja';

SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos WHERE SABOR = 'Manga';

-- LIMITANDO A SAIDA DA CONSULTA
SELECT CPF, NOME, IDADE FROM tabela_de_clientes LIMIT 5;

SELECT CPF, NOME, IDADE FROM tabela_de_clientes LIMIT 2,5;

-- ORDENANDO A SAÍDA DA CONSULTA
SELECT CPF, NOME, IDADE FROM tabela_de_clientes ORDER BY IDADE ASC;

SELECT CPF, NOME, IDADE FROM tabela_de_clientes ORDER BY IDADE DESC;

SELECT NOME_DO_PRODUTO, EMBALAGEM, SABOR, PRECO_DE_LISTA FROM tabela_de_produtos ORDER BY PRECO_DE_LISTA DESC;

-- APLICANDO FUNÇÕES E CONHECENDO O GROUP BY
SELECT SABOR, AVG(PRECO_DE_LISTA) AS MEDIA FROM tabela_de_produtos GROUP BY SABOR;

SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS MEDIA FROM tabela_de_produtos GROUP BY EMBALAGEM;

SELECT SABOR, AVG(PRECO_DE_LISTA) AS MEDIA FROM tabela_de_produtos
GROUP BY SABOR HAVING AVG(PRECO_DE_LISTA) > 10;

-- UTILIZANDO O CASE
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
CASE
	WHEN PRECO_DE_LISTA >= 12 THEN 'A'
    WHEN PRECO_DE_LISTA >= 8 THEN 'B'
    WHEN PRECO_DE_LISTA >= 4 THEN 'C'
	ELSE 'D'
END AS CLASS FROM tabela_de_produtos;

-- APLICANDO JOINS AS CONSULTAS

SELECT COUNT(*) AS CONTAGEM FROM tabela_de_clientes;

SELECT CPF, COUNT(*) AS CONTAGEM FROM notas_fiscais GROUP BY CPF;

SELECT DISTINCT A.CPF, A.NOME, B.CPF FROM tabela_de_clientes A
INNER JOIN notas_fiscais B ON A.CPF = B.CPF;

SELECT DISTINCT A.CPF, A.NOME, B.CPF FROM tabela_de_clientes A
LEFT JOIN notas_fiscais B ON A.CPF = B.CPF;

SELECT DISTINCT A.CPF, A.NOME, B.CPF FROM tabela_de_clientes A
LEFT JOIN notas_fiscais B ON A.CPF = B.CPF WHERE B.CPF IS NULL;

-- JUNTANDO CONSULTAS

SELECT DISTINCT BAIRRO FROM tabela_de_clientes;

SELECT DISTINCT BAIRRO FROM tabela_de_vendedores;

SELECT DISTINCT BAIRRO FROM tabela_de_clientes
UNION
SELECT DISTINCT BAIRRO FROM tabela_de_vendedores;