SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS LIMITE FROM tabela_de_clientes GROUP BY ESTADO;

SELECT ESTADO, AVG(LIMITE_DE_CREDITO) AS LIMITE FROM tabela_de_clientes GROUP BY ESTADO;

SELECT EMBALAGEM, COUNT(*) FROM tabela_de_produtos GROUP BY EMBALAGEM;

SELECT BAIRRO, AVG(LIMITE_DE_CREDITO) AS LIMITE_MEDIO FROM tabela_de_clientes
WHERE CIDADE = 'Rio de Janeiro' GROUP BY BAIRRO

