-- Active: 1672072201697@@127.0.0.1@3306@CLIENTES
# CONTAR TODAS AS LINHAS DA COLUNA ID E DE UM APELIDO PARA A COLUNA RETORNADA
SELECT COUNT(ID) AS 'QUANTIDADE_DE_CLIENTES' FROM DADOS;

# SELECIONAR TODAS AS LINHAS DA TABELA QUE TENHAM SEX = 1 OU QUE LIMIT_BAL < 10000
SELECT * FROM DADOS WHERE SEX = 1 OR LIMIT_BAL < 10000;

# SELECIONAR TODAS AS IDADES DISTINTAS
SELECT DISTINCT AGE AS IDADE FROM DADOS;

# SELECIONAR TODAS AS LINHAS CUJO O LIMIT_BAL NÃO INICIE COM 5
SELECT * FROM DADOS WHERE LIMIT_BAL NOT LIKE '5%';

# SELECIONAR LINHAS ÚNICAS DA TABELA
SELECT DISTINCT SEX AS SEXO FROM DADOS;
