-- Active: 1672072201697@@127.0.0.1@3306@FUNCIONARIOS

# EXPLORANDO TODOS OS DADOS DA TABELA
SELECT * FROM DADOS;

# SELECIONANDO TODOS OS KEVIN DA TABELA
SELECT * FROM DADOS WHERE EmployeeName LIKE 'KEVIN%';

# LIMPANDO OS EMPREGOS ÚNICOS
SELECT DISTINCT `JobTitle` FROM DADOS;

# EXPLORANDO A MÉDIA SALARIAL DE CADA CARGO
SELECT JobTitle AS CARGO, AVG(TotalPay) AS MEDIA_SALARIAL FROM DADOS GROUP BY `JobTitle`;
