-- Active: 1672072201697@@127.0.0.1@3306@CLIENTES

# SELECIONANDO TODAS AS VARIÁVEIS E LINHAS DA TABELA
SELECT * FROM `DADOS`;

# SELECIONANDO DADOS ESPECÍFICOS DA TABELA
SELECT ID, LIMIT_BAL FROM `DADOS`;

# RENOMEANDO COLUNAS
SELECT 
ID AS IDENTIFICADOR,
SEX AS GENERO,
MARRIAGE AS CASADO
FROM DADOS;

# LIMPANDO DADOS REPETIDOS
SELECT DISTINCT `SEX` FROM `DADOS`;

# CONTANDO TODAS AS LINHAS DA TABELA
SELECT COUNT(*) AS 'QUANTIDADE DE DADOS' FROM DADOS;

# TRABALHANDO COM CONDICIONAL I
SELECT * FROM DADOS WHERE SEX = 1;

# TRABALHANDO COM CONDICIONAL II
SELECT COUNT(*) FROM DADOS WHERE SEX = 2;

# TRABALHANDO COM CONDICIONAL COMPOSTA I
SELECT * FROM DADOS WHERE EDUCATION = 1 AND SEX = 1;

# TRABALHANDO COM CONDICIONAL COMPOSTA II
SELECT * FROM DADOS WHERE EDUCATION = 1 OR MARRIAGE = 1;

# OPERADOR LIKE
SELECT * FROM DADOS WHERE LIMIT_BAL LIKE '5%';

# OPERADOR NOT LIKE
SELECT * FROM DADOS WHERE LIMIT_BAL NOT LIKE '5%';

# FUNÇÕES I : SUM()
SELECT SEX, SUM(LIMIT_BAL) FROM DADOS GROUP BY SEX;

# FUNÇÕES II : AVG()
SELECT SEX, AVG(LIMIT_BAL) FROM DADOS GROUP BY SEX;

# FUNÇÕES III : MIN()
SELECT SEX, MIN(LIMIT_BAL) FROM DADOS GROUP BY SEX;

