# CRIANDO UM SCHEMA DE EXEMPLO
CREATE DATABASE SUCOS;

# CONFIGURANDO A EXECUÇÃO NO SCHEMA DESEJÁVEL
USE SUCOS;

# CRIANDO UMA TABELA
CREATE TABLE CLIENTES(
	CPF VARCHAR(11),
    NOME VARCHAR(100),
    ENDERECO1 VARCHAR(150),
    ENDERECO2 VARCHAR(150),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(50),
    CEP VARCHAR(8),
    IDADE SMALLINT,
    SEXO VARCHAR(1),
    LIMITE_DE_CREDITO FLOAT,
    VOLUME_DE_COMPRA FLOAT,
    PRIMEIRA_COMPRA BIT(1)
);

CREATE TABLE PRODUTOS (
	PRODUTO VARCHAR(50),
    NOME VARCHAR(50),
    EMBALAGEM VARCHAR(25),
    TAMANHO VARCHAR(25),
    SABOR VARCHAR(25),
    PRECO_DE_LISTA DOUBLE
);

# DELETANDO UMA TABELA
CREATE TABLE TABELA1 (
	NUMERO INT,
    TEXTO VARCHAR(12),
    LOGICO BOOLEAN
);

CREATE TABLE TABELA2 (
	NUMERO INT,
    TEXTO VARCHAR(12),
    LOGICO BOOLEAN
);

CREATE TABLE TABELA3 (
	NUMERO INT,
    TEXTO VARCHAR(12),
    LOGICO BOOLEAN
);

DROP TABLE TABELA1;
DROP TABLE TABELA2;
DROP TABLE TABELA3;