USE sucos;

-- SELECIONANDO TODOS OS CAMPOS DA TABELA
SELECT * FROM tbcliente;

-- SELECIONANDO CAMPOS ESPECÍFICOS DA TABELA
SELECT CPF, NOME, IDADE, BAIRRO, ESTADO FROM tbcliente;

-- SELECTIONANDO CAMPOS ESPECÍFICOS COM UM LIMITE
SELECT CPF, NOME, IDADE, BAIRRO, ESTADO FROM tbcliente LIMIT 5;

-- SELECIONANDO NOMES E ALTERANDO A APRESENTAÇÃO
SELECT CPF AS CPF, NOME AS NAME, IDADE AS AGE, BAIRRO, ESTADO FROM tbcliente LIMIT 5;

-- SELECIONANDO DADOS COM UM CAMPO EM COMUM
SELECT * FROM tbproduto WHERE SABOR = 'Laranja';

-- MUDANDO TODOS OS VALORES DE UM CAMPO ATRÁVES DE UMA CONDIÇÃO
UPDATE tbproduto SET SABOR = 'Cítricos' WHERE SABOR = 'Limão';

-- FAZENDO CONDIÇÕES DIFERENTES
SELECT CPF, NOME, IDADE FROM tbcliente WHERE IDADE = 22;

SELECT CPF, NOME, IDADE FROM tbcliente WHERE IDADE > 22;

SELECT CPF, NOME, IDADE FROM tbcliente WHERE IDADE < 22;

SELECT CPF, NOME, IDADE FROM tbcliente WHERE IDADE >= 22;

SELECT CPF, NOME, IDADE FROM tbcliente WHERE IDADE != 22;

SELECT CPF, NOME, IDADE FROM tbcliente WHERE IDADE <> 22;

-- TRABALHANDO COM DATAS
SELECT CPF, NOME, DATA_NASCIMENTO FROM tbcliente WHERE DATA_NASCIMENTO > '1990-01-01';

SELECT CPF, NOME, DATA_NASCIMENTO FROM tbcliente WHERE DATA_NASCIMENTO < '1990-01-01';

SELECT CPF, NOME, DATA_NASCIMENTO FROM tbcliente WHERE YEAR(DATA_NASCIMENTO) = '1995';

SELECT CPF, NOME, DATA_NASCIMENTO FROM tbcliente WHERE MONTH(DATA_NASCIMENTO) = '08';

-- CONSULTAS COMPOSTAS
SELECT * FROM tbproduto WHERE PRECO_LISTA BETWEEN 2 AND 4;

SELECT * FROM tbproduto WHERE PRECO_LISTA >= 2 AND PRECO_LISTA <= 4;

SELECT CPF, NOME, IDADE, CIDADE, BAIRRO FROM tbcliente WHERE ESTADO = 'SP' or ESTADO = 'RJ';

